@pmv_si_2024_2_pe6_t2_g06_gestao_de_salao_servico_usuario_HostAddress = http://localhost:5211

GET {{pmv_si_2024_2_pe6_t2_g06_gestao_de_salao_servico_usuario_HostAddress}}/weatherforecast/
Accept: application/json

###
